config/routes.rb
Rails.application.routes.draw do
  get 'user/show'
  devise_for :users
  resources :users, only: [:show]
  root to: 'home#index'
  resources :home, only: :index
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  validates :title, :content, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.page(params[:page]).per(10).order("created_at desc")
  end

  def new
  	@question = Question.new
  end

  def create
  	@question = current_user.questions.build(question_params)

  	if @question.save
  	  redirect_to question_path(@question), notice: 'Question was successfully created.'
  	else
  		redirect_to new_question_path(@question), notice: 'Title and content must be filled in.'
  	end
  end

  def show
  	@question = Question.find(params[:id])
  end

  private

  def question_params
  	params.require(:question).permit(:title, :content, :tag_list)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def name:string
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container text-center pt-3">
  Welcome to AskMe!
</div>
<% if user_signed_in? %>
	<h3><%= link_to 'Dodaj pytanie', new_question_path %></h3>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, class: "alert alert-#{name == 'notice' ? 'success' : 'danger' }" %>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'AskMe', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to 'Questions', questions_path, class: 'nav-link' %>
      </li>
    </ul>
    <% if current_user %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      <%= link_to 'My profile', user_path(current_user), class: 'nav-link' %>
    <% else %>
      <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    <div>
  </body>
</html>

app/views/questions/index.html.erb
<p><h5>Question List</h5></p>
<div class="container pt-3">
  <% @questions.each do |question| %>
    <div class="container question-box">
      <p><%= link_to "#{question.title}", question_path(question) %></p>
    </div>
  <% end %>
  <%= paginate @questions %>
</div>

app/views/questions/new.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= raw t('errors.template.header', count: @question.errors.count, model: t('activerecord.models.order')) %></h2>
      <p><%= t('errors.template.body') %></p>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= raw message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title, t('.title') %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content, t('.content') %>
    <%= f.text_area :content %>
  </div>

  <div>
    <%= f.label :tag_list, t('.tags') %>
    <%= f.text_area :tag_list %>
  </div>

  <div>
    <%= f.submit 'Dodaj pytanie' %>
  </div>
<% end %>

app/views/questions/show.html.erb
<h2><%= @question.title %></h2>
<p><%= @question.content %></p>
<p>Tagi:</p>
<lu>
<% @question.tag_list.split(',').uniq.each do |tag| %>
	<li><%= tag %></li>
<% end %>
</lu>

<p><%= @question.created_at %></p>
<p><%= "Asked by #{@question.user.email}" %></p>

<%= link_to 'Back', root_path %>

app/views/tags/name:string.html.erb
<h1>Tags#name:string</h1>
<p>Find me in app/views/tags/name:string.html.erb</p>

app/views/users/show.html.erb
<%= @user.email %>